name: Deploy to Netsons

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload via FTPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTPS Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps-legacy
          port: 21
          security: loose
          timeout: 120000
          local-dir: ./
          server-dir: ./public_html/
          exclude: |
            **/.git*
            **/.github/**
            **/README.md
            docker-compose.yml
            Dockerfile
            ddns-config.json
            apps/modus/**